#!/usr/bin/bash

VERBOSE_OUTPUT=0
ADD_DATE_TO_FILENAME=""

usage() {
    cat <<EOL
    Usage: $0 [OPTIONS] <source_dir> <backup_name>
    Options:
        -v              : Verbose mode.
        --date <format> : Add date to the backup filename.
                          Supported formats: time, date, datetime, timestamp
    EOL
}


if [[ $# -lt 2 ]]; then
    usage
    exit 1
fi

while true; do
    case $1 in
        -v)
            VERBOSE_OUTPUT=1
            shift 1
            ;;
        --date)
            case $2 in
                time)
                    ADD_DATE_TO_FILENAME=$(date +%H%M%S)
                    ;;
                date)
                    ADD_DATE_TO_FILENAME=$(date +%Y%m%d)
                    ;;
                datetime)
                    ADD_DATE_TO_FILENAME=$(date +%Y%m%d-%H%M%S)
                    ;;
                timestamp)
                    ADD_DATE_TO_FILENAME=$(date +%s)
                    ;;
                *)
                    echo "ERROR: Unsupported date format."
                    exit 1
                    ;;
            esac
            shift 2
            ;;
        *)
            break
            ;;
    esac
done
